version: "3"
services:
  mongodb:
    build:
      context: .
      dockerfile: mongodb/Dockerfile
    container_name: "warehouse-db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: warehouse
      MONGO_DB_USERNAME: user
      MONGO_DB_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - warehouse-network
    command: ["--bind_ip", "0.0.0.0"]
networks:
  warehouse-network:
    driver: bridge